services:
  portfolio.server:
    image: portfolio.server:dev
    container_name: "portfolio.Server_1"
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "portfolio.Server"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\se1c8x\project\Ayham-project\portfolio\portfolio.Server:/app:rw
      - C:\Users\se1c8x\project\Ayham-project\portfolio\portfolio.Server:/src:rw
      - C:\Users\se1c8x\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\se1c8x\.nuget\packages:/.nuget/packages:ro
      - C:\Users\se1c8x\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\se1c8x\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\se1c8x\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\se1c8x\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/portfolio.Server.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true